# Generated by Django 4.1.5 on 2024-03-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('masala', 'color'), ('size', 'size')], max_length=100),
        ),
    ]
