# Generated by Django 5.0 on 2024-04-17 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='payment',
            field=models.ForeignKey(blank=True, default='cash on delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.payment'),
        ),
    ]
