# Generated by Django 5.0 on 2024-04-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_variation_variation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('marination', 'Marination'), ('cut_pieces', 'Cut into Pieces'), ('cut_fillings', 'Cut for Fillings'), ('cleaned_deveined', 'Cleaned and Deveined')], max_length=100),
        ),
    ]
