# Generated by Django 5.0 on 2024-04-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_variation_variation_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='image_slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/img/slider')),
            ],
        ),
    ]
