# Generated by Django 5.0 on 2025-02-01 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cartitem_variation'),
        ('orders', '0016_remove_orderproduct_variations_ordervariation'),
        ('shop', '0015_alter_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('variation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.variationtype')),
            ],
            options={
                'unique_together': {('product', 'variation_type')},
            },
        ),
        migrations.CreateModel(
            name='PredefinedVariationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('additional_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('variation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.variationtype')),
            ],
            options={
                'unique_together': {('variation_type', 'value')},
            },
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
