# Generated by Django 5.0 on 2025-02-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_variationtype_productvariation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variationtype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
