# Generated by Django 5.0 on 2025-02-01 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_cartitem_variations'),
        ('orders', '0018_remove_ordervariation_order_product_and_more'),
        ('shop', '0017_variationtype_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='variation_type',
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_category', models.CharField(choices=[('marination', 'Marination'), ('cut_pieces', 'Cut into Pieces'), ('cut_fillings', 'Cut for Fillings'), ('cleaned_deveined', 'Cleaned and Deveined')], max_length=100)),
                ('variation_value', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.DeleteModel(
            name='PredefinedVariationValue',
        ),
        migrations.DeleteModel(
            name='ProductVariation',
        ),
        migrations.DeleteModel(
            name='VariationType',
        ),
    ]
