# Generated by Django 5.0 on 2025-04-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_product_of_the_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_of_the_day',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
