# Generated by Django 5.0 on 2025-04-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_product_of_the_day_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_of_the_day',
            name='image',
            field=models.ImageField(default='product_of_the_day', upload_to='product_of_the_day'),
        ),
    ]
