# Generated by Django 5.0 on 2025-08-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_product_of_the_day_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionalBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('vb1', 'Vitamin B1'), ('vb2', 'Vitamin B2'), ('vb12', 'Vitamin B12'), ('vb6', 'Vitamin B6'), ('proteins', 'Proteins'), ('omega_fatty_acids', 'Omega Fatty Acids'), ('calcium', 'Calcium'), ('low_fat_diet', 'Low Fat Diet'), ('iron_zinc', 'Iron & Zinc')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Nutritional Benefit',
                'verbose_name_plural': 'Nutritional Benefits',
                'ordering': ['display_name'],
            },
        ),
        migrations.RemoveField(
            model_name='product_of_the_day',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product_of_the_day',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='nutritional_benefits',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.nutritionalbenefit'),
        ),
    ]
