# Generated by Django 5.0 on 2025-09-10 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_nutritionalbenefit_remove_product_of_the_day_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('raw_fish', 'RAW FISH'), ('dry_fish', 'DRY FISH'), ('pickles', 'PICKLES'), ('masala', 'MASALA')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Feature Category',
                'verbose_name_plural': 'Feature Categories',
                'ordering': ['display_name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='feature_category',
            field=models.ForeignKey(blank=True, help_text='Required: Select the feature category this product belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.featurecategory'),
        ),
    ]
