# Generated by Django 5.0 on 2024-04-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='timing_slot',
            field=models.CharField(choices=[('9-11', 'Pre-order - 9-11 am'), ('12-1', 'Morning orders delivered by 12-1 pm'), ('7-9', 'Evening slot - 7-9 pm')], default='9-11', max_length=5),
        ),
    ]
