# Generated by Django 5.0 on 2024-04-29 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_timing_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='timing_slot',
        ),
    ]
