# Generated by Django 5.0 on 2025-02-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cartitem_variation'),
        ('shop', '0016_variationtype_productvariation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='shop.predefinedvariationvalue'),
        ),
    ]
