# Generated by Django 5.0 on 2024-04-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_timingslot_order_timing_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='selected_timing_slot',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
