# Generated by Django 5.0 on 2024-04-30 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_selected_timing_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='selected_timing_slot',
        ),
    ]
