# Generated by Django 5.0 on 2025-01-05 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_payment_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Razorpay', 'Razorpay'), ('COD', 'Cash On Delivery')], max_length=20),
        ),
        migrations.CreateModel(
            name='CODPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('otp_verified', models.BooleanField(default=False)),
                ('otp_generated_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.payment')),
            ],
        ),
    ]
