# Generated by Django 5.0 on 2025-02-01 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_remove_orderproduct_variations_ordervariation'),
        ('shop', '0016_variationtype_productvariation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordervariation',
            name='variation_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.predefinedvariationvalue'),
        ),
    ]
