# Generated by Django 5.0 on 2025-02-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_remove_ordervariation_order_product_and_more'),
        ('shop', '0018_alter_productvariation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='variations',
            field=models.ManyToManyField(blank=True, to='shop.variation'),
        ),
        migrations.DeleteModel(
            name='OrderVariation',
        ),
    ]
